name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build exlaunch
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
        fetch-tags: true
    - name: Install group switch-dev
      run: dkp-pacman -S --noconfirm switch-dev
    - name: Build
      run: make
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: |
          deploy/main.npdm
          deploy/subsdk9

  release:
    runs-on: 'ubuntu-latest'
    needs:
      - build
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: binaries
      - name: Create GitHub release
        uses: svenstaro/upload-release-action@2.9.0
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
          body: "New release"